package kome.common.config;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;

/** Immutable effective-value differences between two validated configuration snapshots. */
public final class KOMEConfigChangeSet {
    private final List<Entry> entries;
    private KOMEConfigChangeSet(List<Entry> entries) {
        Collections.sort(entries, ORDER);
        this.entries = Collections.unmodifiableList(new ArrayList<Entry>(entries));
    }
    public boolean isEmpty() { return entries.isEmpty(); }
    public List<Entry> getEntries() { return entries; }
    public static KOMEConfigChangeSet compare(KOMEConfigRegistry.ValidatedConfig a,
            KOMEConfigRegistry.ValidatedConfig b) {
        List<Entry> r = new ArrayList<Entry>();
        add(r,"dailyBatch","localTime",a.getDailyBatch().getLocalTime(),b.getDailyBatch().getLocalTime()); add(r,"dailyBatch","timezone",a.getDailyBatch().getTimezone(),b.getDailyBatch().getTimezone());
        add(r,"population","hoursPerPopulationPoint",a.getPopulation().getHoursPerPopulationPoint(),b.getPopulation().getHoursPerPopulationPoint()); add(r,"population","capturedBuildMultiplier",a.getPopulation().getCapturedBuildMultiplier(),b.getPopulation().getCapturedBuildMultiplier()); add(r,"population","offlinePopulationCatchUp",a.getPopulation().isOfflinePopulationCatchUp(),b.getPopulation().isOfflinePopulationCatchUp()); add(r,"population","populationCapEnabled",a.getPopulation().isPopulationCapEnabled(),b.getPopulation().isPopulationCapEnabled()); add(r,"population","populationCapValue",a.getPopulation().getPopulationCapValue(),b.getPopulation().getPopulationCapValue()); add(r,"population","encirclementPopulationSuppressionEnabled",a.getPopulation().isEncirclementPopulationSuppressionEnabled(),b.getPopulation().isEncirclementPopulationSuppressionEnabled()); add(r,"population","unitPopulationCostOverrides",a.getPopulation().getUnitPopulationCostOverrides(),b.getPopulation().getUnitPopulationCostOverrides());
        add(r,"movement","footOrMixedTilesPerDay",a.getMovement().getFootOrMixedTilesPerDay(),b.getMovement().getFootOrMixedTilesPerDay()); add(r,"movement","fullyMountedTilesPerDay",a.getMovement().getFullyMountedTilesPerDay(),b.getMovement().getFullyMountedTilesPerDay());
        add(r,"battle","responseLevel1Minutes",a.getBattle().getResponseLevel1Minutes(),b.getBattle().getResponseLevel1Minutes()); add(r,"battle","responseLevel2Minutes",a.getBattle().getResponseLevel2Minutes(),b.getBattle().getResponseLevel2Minutes()); add(r,"battle","responseLevel3Minutes",a.getBattle().getResponseLevel3Minutes(),b.getBattle().getResponseLevel3Minutes());
        add(r,"muster","threatDistanceTiles",a.getMuster().getThreatDistanceTiles(),b.getMuster().getThreatDistanceTiles()); add(r,"muster","budgetDailyPopulationMultiplier",a.getMuster().getBudgetDailyPopulationMultiplier(),b.getMuster().getBudgetDailyPopulationMultiplier()); add(r,"muster","arrivalDelayHours",a.getMuster().getArrivalDelayHours(),b.getMuster().getArrivalDelayHours()); add(r,"muster","encircledCapitalArrivalPolicy",a.getMuster().getEncircledCapitalArrivalPolicy(),b.getMuster().getEncircledCapitalArrivalPolicy());
        add(r,"siege","gateHpPerApprovedHour",a.getSiege().getGateHpPerApprovedHour(),b.getSiege().getGateHpPerApprovedHour()); add(r,"siege","normalSegmentSupportMinimumTroops",a.getSiege().getNormalSegmentSupportMinimumTroops(),b.getSiege().getNormalSegmentSupportMinimumTroops()); add(r,"siege","supportFallbackGraceSeconds",a.getSiege().getSupportFallbackGraceSeconds(),b.getSiege().getSupportFallbackGraceSeconds()); add(r,"siege","preBreachRepair",a.getSiege().getPreBreachRepair(),b.getSiege().getPreBreachRepair()); add(r,"siege","postBreachRepairEnabled",a.getSiege().isPostBreachRepairEnabled(),b.getSiege().isPostBreachRepairEnabled()); add(r,"siege","exteriorMarginBlocks",a.getSiege().getExteriorMarginBlocks(),b.getSiege().getExteriorMarginBlocks());
        add(r,"siege","activeSiegeCheckInWindowMinutes",a.getSiege().getActiveSiegeCheckInWindowMinutes(),b.getSiege().getActiveSiegeCheckInWindowMinutes());
        add(r,"battleSupport","mode",a.getBattleSupport().getMode(),b.getBattleSupport().getMode()); add(r,"battleSupport","fullDamageDistanceBlocks",a.getBattleSupport().getFullDamageDistanceBlocks(),b.getBattleSupport().getFullDamageDistanceBlocks()); add(r,"battleSupport","halfDamageDistanceBlocks",a.getBattleSupport().getHalfDamageDistanceBlocks(),b.getBattleSupport().getHalfDamageDistanceBlocks()); add(r,"battleSupport","lowDamageDistanceBlocks",a.getBattleSupport().getLowDamageDistanceBlocks(),b.getBattleSupport().getLowDamageDistanceBlocks()); add(r,"battleSupport","minimumDamageDistanceBlocks",a.getBattleSupport().getMinimumDamageDistanceBlocks(),b.getBattleSupport().getMinimumDamageDistanceBlocks()); add(r,"battleSupport","halfDamageMultiplier",a.getBattleSupport().getHalfDamageMultiplier(),b.getBattleSupport().getHalfDamageMultiplier()); add(r,"battleSupport","lowDamageMultiplier",a.getBattleSupport().getLowDamageMultiplier(),b.getBattleSupport().getLowDamageMultiplier()); add(r,"battleSupport","minimumDamageMultiplier",a.getBattleSupport().getMinimumDamageMultiplier(),b.getBattleSupport().getMinimumDamageMultiplier()); add(r,"battleSupport","hardFallbackDistanceBlocks",a.getBattleSupport().getHardFallbackDistanceBlocks(),b.getBattleSupport().getHardFallbackDistanceBlocks()); add(r,"battleSupport","openBattleRadiusBlocks",a.getBattleSupport().getOpenBattleRadiusBlocks(),b.getBattleSupport().getOpenBattleRadiusBlocks());
        add(r,"encirclement","starvationGraceDays",a.getEncirclement().getStarvationGraceDays(),b.getEncirclement().getStarvationGraceDays()); add(r,"encirclement","announcedAssaultNoticeHours",a.getEncirclement().getAnnouncedAssaultNoticeHours(),b.getEncirclement().getAnnouncedAssaultNoticeHours()); add(r,"encirclement","offlineStarvationCatchUp",a.getEncirclement().isOfflineStarvationCatchUp(),b.getEncirclement().isOfflineStarvationCatchUp()); add(r,"season","minimumWarSeasonLengthDays",a.getSeason().getMinimumWarSeasonLengthDays(),b.getSeason().getMinimumWarSeasonLengthDays()); add(r,"season","automaticFinaleEnabled",a.getSeason().isAutomaticFinaleEnabled(),b.getSeason().isAutomaticFinaleEnabled());
        return new KOMEConfigChangeSet(r);
    }
    private static void add(List<Entry> r,String c,String k,Object a,Object b){String x=format(a),y=format(b);if(!x.equals(y))r.add(new Entry(c,k,x,y));}
    private static String format(Object v){if(v instanceof java.util.OptionalInt)return ((java.util.OptionalInt)v).isPresent()?Integer.toString(((java.util.OptionalInt)v).getAsInt()):"TBD";if(v instanceof java.util.OptionalDouble)return ((java.util.OptionalDouble)v).isPresent()?Double.toString(((java.util.OptionalDouble)v).getAsDouble()):"TBD";if(v instanceof Enum)return ((Enum)v).name();return String.valueOf(v);}
    private static final Comparator<Entry> ORDER=new Comparator<Entry>(){public int compare(Entry a,Entry b){int r=a.category.compareTo(b.category);return r==0?a.key.compareTo(b.key):r;}};
    public static final class Entry {private final String category,key,oldValue,newValue;private Entry(String c,String k,String o,String n){category=c;key=k;oldValue=o;newValue=n;}public String getCategory(){return category;}public String getKey(){return key;}public String getOldValue(){return oldValue;}public String getNewValue(){return newValue;}public String getCanonicalKey(){return category+"."+key;}}
}
