package com.enovak.lotrmoremobs.siege.edit;

/** Bounded server result codes for the transient edit-session protocol. */
public enum GateEditStatus {
    OPENED, CANCELLED, ACTION_ACCEPTED, NO_INSPECTION, NO_PERMISSION, GATE_UNAVAILABLE,
    UUID_MISMATCH, STALE_REVISION, OWNERSHIP_MISMATCH, EDIT_LEASED,
    EDIT_SESSION_ACTIVE, TOKEN_MISMATCH, SESSION_EXPIRED, WRONG_DIMENSION,
    TOO_FAR, CHUNK_UNLOADED, INVALID_SOURCE, ALREADY_IN_DRAFT, NOT_IN_DRAFT,
    NOT_OWNED_GATEPART, FOREIGN_OWNER, INVALID_ROLE, INVALID_HINGE, PART_LIMIT,
    WIDTH_LIMIT, HEIGHT_LIMIT, THICKNESS_LIMIT, SOURCE_CHANGED, RATE_LIMITED,
    MUTATION_IN_PROGRESS
}
