package kome.common.network;
import cpw.mods.fml.common.network.simpleimpl.*;import io.netty.buffer.ByteBuf;import kome.common.KOMEReflection;import kome.common.data.*;import lotr.common.entity.npc.LOTREntityNPC;import net.minecraft.entity.Entity;import net.minecraft.entity.player.EntityPlayerMP;import net.minecraft.util.ChatComponentText;
/** One narrow server boundary for Talk and Service from the relationship hub. */
public class KOMEPacketRelationshipAction implements IMessage {
 public static final int MASTER=0,LIEGE=1,TALK=0,SERVICE=1; public int entityId,relationship,action;
 public KOMEPacketRelationshipAction(){} public KOMEPacketRelationshipAction(int id,int r,int a){entityId=id;relationship=r;action=a;}
 public void fromBytes(ByteBuf b){entityId=b.readInt();relationship=b.readByte();action=b.readByte();} public void toBytes(ByteBuf b){b.writeInt(entityId);b.writeByte(relationship);b.writeByte(action);}
 public static void sendHub(EntityPlayerMP p,LOTREntityNPC n,int relationship){KOMEPacketHandler.network.sendTo(new KOMEPacketRelationshipHub(n.getEntityId(),relationship,n.getNPCName(),n.getFaction()==null?"":n.getFaction().factionName()),p);}
 public static class Handler implements IMessageHandler<KOMEPacketRelationshipAction,IMessage>{public IMessage onMessage(KOMEPacketRelationshipAction m,MessageContext c){EntityPlayerMP p=c.getServerHandler().playerEntity;if((m.relationship!=MASTER&&m.relationship!=LIEGE)||(m.action!=TALK&&m.action!=SERVICE)){p.addChatMessage(new ChatComponentText("Unknown relationship action."));return null;}Entity e=KOMEReflection.getWorld(p).getEntityByID(m.entityId);if(!(e instanceof LOTREntityNPC)||!e.isEntityAlive()||p.getDistanceSqToEntity(e)>64){p.addChatMessage(new ChatComponentText("That relationship NPC is no longer available."));return null;}LOTREntityNPC n=(LOTREntityNPC)e;KOMEWorldData d=KOMEWorldData.get(KOMEReflection.getWorld(p));KOMEPlayerProgression q=d.getProgression(KOMEReflection.getEntityUUID(p));KOMESerfKnightProgression s=q.getSerfKnightProgression();KOMEProgressionNpcRef ref=KOMEProgressionNpcRankService.referenceOf(n);boolean exact=m.relationship==MASTER?s.getSerfdomMaster().hasSameIdentity(ref):s.getProspectiveLiege().hasSameIdentity(ref);if(!exact||q.getCanonicalRank()!=KOMEProgressionRank.SERF){p.addChatMessage(new ChatComponentText("That is not your current relationship NPC."));return null;}if(m.action==TALK){n.interactFirst(p);return null;}if(m.relationship==MASTER){KOMESerfdomMasterService.Result valid=KOMESerfdomMasterService.validateCurrentMasterInteraction(p,d,n,true);if(!valid.success){p.addChatMessage(new ChatComponentText(valid.reason));return null;}KOMEPacketSerfdomMasterAction.sendMenu(p,n);return null;}KOMEPacketHandler.network.sendTo(new KOMEPacketLordMenu(n.getEntityId(),n.getNPCName(),n.getFaction()==null?"":n.getFaction().factionName(),true),p);return null;}}
}
