package com.enovak.lotrmoremobs.siege.network;

import com.enovak.lotrmoremobs.Main;
import com.enovak.lotrmoremobs.siege.edit.*;
import com.enovak.lotrmoremobs.siege.gate.*;
import cpw.mods.fml.common.network.simpleimpl.*;
import io.netty.buffer.ByteBuf;
import java.util.*;

/** Full bounded S2C mirror of the transient draft; it intentionally excludes source provenance. */
public final class GateEditDraftSnapshotPacket implements IMessage {
    public enum VisualKind { ORIGINAL_RETAINED, ORIGINAL_ROLE_CHANGED, ADDED }
    public static final class Part { public final int x,y,z; public final GateLeaf leaf; public final VisualKind kind; Part(int x,int y,int z,GateLeaf leaf,VisualKind kind){this.x=x;this.y=y;this.z=z;this.leaf=leaf;this.kind=kind;} }
    private UUID token,gateUuid; private int dimension,x,y,z,revision; private long sequence; private GateOrientation orientation; private GateOpeningDirection direction; private boolean borderTextureEnabled; private GateHinge leftHinge,rightHinge; private List<Part> parts=Collections.emptyList(); private boolean valid;
    public GateEditDraftSnapshotPacket(){}
    public GateEditDraftSnapshotPacket(GateEditSession session){if(session==null)throw new IllegalArgumentException("Edit session required.");token=session.getSessionToken();gateUuid=session.getGateUuid();dimension=session.getDimensionId();x=session.getControllerX();y=session.getControllerY();z=session.getControllerZ();revision=session.getBaseRevision();sequence=session.getDraftSequence();GateEditDraft d=session.getDraft();orientation=d.getOrientation();direction=d.getOpeningDirection();borderTextureEnabled=d.isBorderTextureEnabled();leftHinge=d.getLeftHinge();rightHinge=d.getRightHinge();List<Part> out=new ArrayList<Part>();for(GateEditDraftPart p:d.getParts()){VisualKind kind=!p.originatesFromOriginal()?VisualKind.ADDED:originalLeaf(session,p)==p.getLeaf()?VisualKind.ORIGINAL_RETAINED:VisualKind.ORIGINAL_ROLE_CHANGED;out.add(new Part(p.getRelativeX(),p.getRelativeY(),p.getRelativeZ(),p.getLeaf(),kind));}parts=Collections.unmodifiableList(out);valid=true;}
    private static GateLeaf originalLeaf(GateEditSession s,GateEditDraftPart p){for(GateEditOriginalPart o:s.getOriginal().getParts())if(o.getRelativeX()==p.getRelativeX()&&o.getRelativeY()==p.getRelativeY()&&o.getRelativeZ()==p.getRelativeZ())return o.getLeaf();return null;}
    public void fromBytes(ByteBuf b){valid=false;try{token=new UUID(b.readLong(),b.readLong());gateUuid=new UUID(b.readLong(),b.readLong());dimension=b.readInt();x=b.readInt();y=b.readInt();z=b.readInt();revision=b.readInt();sequence=b.readLong();orientation=readEnum(b,GateOrientation.values());direction=readEnum(b,GateOpeningDirection.values());borderTextureEnabled=b.readBoolean();leftHinge=readHinge(b);rightHinge=readHinge(b);int count=b.readUnsignedShort();if(count>GateStructureValidator.MAX_GATE_PARTS)throw new IllegalArgumentException();List<Part> out=new ArrayList<Part>(count);for(int i=0;i<count;i++){GateLeaf leaf=GateLeaf.fromWireId(b.readUnsignedByte());int kind=b.readUnsignedByte();if(leaf==null||kind>=VisualKind.values().length)throw new IllegalArgumentException();out.add(new Part(b.readInt(),b.readInt(),b.readInt(),leaf,VisualKind.values()[kind]));}parts=Collections.unmodifiableList(out);valid=true;}catch(RuntimeException e){parts=Collections.emptyList();}}
    public void toBytes(ByteBuf b){if(!valid||token==null||gateUuid==null||parts.size()>GateStructureValidator.MAX_GATE_PARTS)throw new IllegalStateException("Invalid draft sync.");b.writeLong(token.getMostSignificantBits());b.writeLong(token.getLeastSignificantBits());b.writeLong(gateUuid.getMostSignificantBits());b.writeLong(gateUuid.getLeastSignificantBits());b.writeInt(dimension);b.writeInt(x);b.writeInt(y);b.writeInt(z);b.writeInt(revision);b.writeLong(sequence);writeEnum(b,orientation);writeEnum(b,direction);b.writeBoolean(borderTextureEnabled);writeHinge(b,leftHinge);writeHinge(b,rightHinge);b.writeShort(parts.size());for(Part p:parts){b.writeByte(p.leaf.getWireId());b.writeByte(p.kind.ordinal());b.writeInt(p.x);b.writeInt(p.y);b.writeInt(p.z);}}
    private static <E extends Enum<E>> E readEnum(ByteBuf b,E[] values){int i=b.readByte();if(i<0||i>=values.length)throw new IllegalArgumentException();return values[i];} private static void writeEnum(ByteBuf b,Enum<?> e){b.writeByte(e==null?-1:e.ordinal());}
    private static GateHinge readHinge(ByteBuf b){if(!b.readBoolean())return null;int rx=b.readInt(),rz=b.readInt(),s=b.readByte();GateHingeSide side=s<0?null:(s>=GateHingeSide.values().length?null:GateHingeSide.values()[s]);return new GateHinge(rx,rz,side);} private static void writeHinge(ByteBuf b,GateHinge h){b.writeBoolean(h!=null);if(h!=null){b.writeInt(h.getRelativeX());b.writeInt(h.getRelativeZ());b.writeByte(h.getSide()==null?-1:h.getSide().ordinal());}}
    public boolean isValid(){return valid;} public UUID getToken(){return token;} public UUID getGateUuid(){return gateUuid;} public int getDimension(){return dimension;} public int getX(){return x;} public int getY(){return y;} public int getZ(){return z;} public int getRevision(){return revision;} public long getSequence(){return sequence;} public GateOrientation getOrientation(){return orientation;} public GateOpeningDirection getDirection(){return direction;} public boolean isBorderTextureEnabled(){return borderTextureEnabled;} public GateHinge getLeftHinge(){return leftHinge;} public GateHinge getRightHinge(){return rightHinge;} public List<Part> getParts(){return parts;}
    public static final class Handler implements IMessageHandler<GateEditDraftSnapshotPacket,IMessage>{public IMessage onMessage(GateEditDraftSnapshotPacket m,MessageContext c){if(m.isValid())Main.proxy.handleGateEditDraftSnapshot(m);return null;}}
}
