package com.enovak.lotrmoremobs.siege.network;

import com.enovak.lotrmoremobs.Main;
import com.enovak.lotrmoremobs.siege.edit.*;
import com.enovak.lotrmoremobs.siege.gate.GateState;
import com.enovak.lotrmoremobs.siege.gate.GateStructureValidator;
import cpw.mods.fml.common.network.simpleimpl.*;
import io.netty.buffer.ByteBuf;
import java.util.*;

/** Bounded S2C informational preflight receipt; it intentionally omits provenance and ownership records. */
public final class GateEditPreflightSnapshotPacket implements IMessage {
    public static final class Issue { public final GateEditPreflightIssueCode code; public final int count; Issue(GateEditPreflightIssueCode code,int count){this.code=code;this.count=count;} }
    private UUID token,gateUuid; private int dimension,x,y,z,revision,currentRevision,partCount,leftCount,rightCount,splitCenterCount,width,height,thickness,changeCount; private long draftSequence,generation;
    private GateEditPreflightState state; private GateEditPreflightIssueCode primaryIssue,structuralIssue; private GateState gateState; private boolean structurallyValid,hasChanges,commitReady,repairActive,ramReserved,valid;
    private List<Issue> issues=Collections.emptyList();
    public GateEditPreflightSnapshotPacket(){}
    public GateEditPreflightSnapshotPacket(GateEditSession session,GateEditPreflightResult result){if(session==null||result==null)throw new IllegalArgumentException("Preflight identity required.");token=session.getSessionToken();gateUuid=session.getGateUuid();dimension=session.getDimensionId();x=session.getControllerX();y=session.getControllerY();z=session.getControllerZ();revision=session.getBaseRevision();draftSequence=result.getDraftSequence();generation=result.getGeneration();state=result.getState();structurallyValid=result.isStructurallyValid();hasChanges=result.hasChanges();commitReady=result.isCommitReady();primaryIssue=result.getPrimaryIssue();structuralIssue=result.getStructural().getPrimaryIssue();partCount=result.getStructural().getPartCount();leftCount=result.getStructural().getLeftCount();rightCount=result.getStructural().getRightCount();splitCenterCount=result.getStructural().getSplitCenterCount();width=result.getStructural().getWidth();height=result.getStructural().getHeight();thickness=result.getStructural().getThickness();changeCount=result.getChangeCount();currentRevision=result.getCurrentRevision();gateState=result.getGateState();repairActive=result.isRepairActive();ramReserved=result.isRamReserved();List<Issue> out=new ArrayList<Issue>();for(GateEditPreflightResult.IssueCount item:result.getIssues())if(out.size()<GateEditPreflightResult.MAX_ISSUES)out.add(new Issue(item.getCode(),item.getCount()));issues=Collections.unmodifiableList(out);valid=true;}
    public void fromBytes(ByteBuf b){valid=false;try{token=new UUID(b.readLong(),b.readLong());gateUuid=new UUID(b.readLong(),b.readLong());dimension=b.readInt();x=b.readInt();y=b.readInt();z=b.readInt();revision=b.readInt();draftSequence=b.readLong();generation=b.readLong();state=readEnum(b,GateEditPreflightState.values());structurallyValid=b.readBoolean();hasChanges=b.readBoolean();commitReady=b.readBoolean();primaryIssue=readEnum(b,GateEditPreflightIssueCode.values());structuralIssue=readEnum(b,GateEditPreflightIssueCode.values());partCount=b.readUnsignedShort();leftCount=b.readUnsignedShort();rightCount=b.readUnsignedShort();splitCenterCount=b.readUnsignedShort();width=b.readUnsignedByte();height=b.readUnsignedByte();thickness=b.readUnsignedByte();changeCount=b.readUnsignedShort();currentRevision=b.readInt();int gateStateId=b.readByte();if(gateStateId>=0){if(gateStateId>=GateState.values().length)throw new IllegalArgumentException();gateState=GateState.values()[gateStateId];}repairActive=b.readBoolean();ramReserved=b.readBoolean();int count=b.readUnsignedByte();if(count>GateEditPreflightResult.MAX_ISSUES)throw new IllegalArgumentException();List<Issue> out=new ArrayList<Issue>(count);for(int i=0;i<count;i++){GateEditPreflightIssueCode code=readEnum(b,GateEditPreflightIssueCode.values());int issueCount=b.readUnsignedShort();if(issueCount<=0)throw new IllegalArgumentException();out.add(new Issue(code,issueCount));}if(token==null||gateUuid==null||revision<=0||partCount>GateStructureValidator.MAX_GATE_PARTS||changeCount>GateStructureValidator.MAX_GATE_PARTS*2)throw new IllegalArgumentException();issues=Collections.unmodifiableList(out);valid=true;}catch(RuntimeException e){issues=Collections.emptyList();}}
    public void toBytes(ByteBuf b){if(!valid||token==null||gateUuid==null||state==null||primaryIssue==null||structuralIssue==null||issues.size()>GateEditPreflightResult.MAX_ISSUES||partCount>GateStructureValidator.MAX_GATE_PARTS||changeCount>GateStructureValidator.MAX_GATE_PARTS*2)throw new IllegalStateException("Invalid preflight snapshot.");b.writeLong(token.getMostSignificantBits());b.writeLong(token.getLeastSignificantBits());b.writeLong(gateUuid.getMostSignificantBits());b.writeLong(gateUuid.getLeastSignificantBits());b.writeInt(dimension);b.writeInt(x);b.writeInt(y);b.writeInt(z);b.writeInt(revision);b.writeLong(draftSequence);b.writeLong(generation);writeEnum(b,state);b.writeBoolean(structurallyValid);b.writeBoolean(hasChanges);b.writeBoolean(commitReady);writeEnum(b,primaryIssue);writeEnum(b,structuralIssue);b.writeShort(partCount);b.writeShort(leftCount);b.writeShort(rightCount);b.writeShort(splitCenterCount);b.writeByte(width);b.writeByte(height);b.writeByte(thickness);b.writeShort(changeCount);b.writeInt(currentRevision);b.writeByte(gateState==null?-1:gateState.ordinal());b.writeBoolean(repairActive);b.writeBoolean(ramReserved);b.writeByte(issues.size());for(Issue issue:issues){writeEnum(b,issue.code);b.writeShort(issue.count);}}
    private static <E extends Enum<E>> E readEnum(ByteBuf b,E[] values){int id=b.readUnsignedByte();if(id>=values.length)throw new IllegalArgumentException();return values[id];} private static void writeEnum(ByteBuf b,Enum<?> value){b.writeByte(value.ordinal());}
    public boolean isValid(){return valid;} public UUID getToken(){return token;} public UUID getGateUuid(){return gateUuid;} public int getDimension(){return dimension;} public int getX(){return x;} public int getY(){return y;} public int getZ(){return z;} public int getRevision(){return revision;} public long getDraftSequence(){return draftSequence;} public long getGeneration(){return generation;} public GateEditPreflightState getState(){return state;} public boolean isStructurallyValid(){return structurallyValid;} public boolean hasChanges(){return hasChanges;} public boolean isCommitReady(){return commitReady;} public GateEditPreflightIssueCode getPrimaryIssue(){return primaryIssue;} public GateEditPreflightIssueCode getStructuralIssue(){return structuralIssue;} public int getPartCount(){return partCount;} public int getLeftCount(){return leftCount;} public int getRightCount(){return rightCount;} public int getSplitCenterCount(){return splitCenterCount;} public int getWidth(){return width;} public int getHeight(){return height;} public int getThickness(){return thickness;} public int getChangeCount(){return changeCount;} public int getCurrentRevision(){return currentRevision;} public GateState getGateState(){return gateState;} public boolean isRepairActive(){return repairActive;} public boolean isRamReserved(){return ramReserved;} public List<Issue> getIssues(){return issues;}
    public static final class Handler implements IMessageHandler<GateEditPreflightSnapshotPacket,IMessage>{public IMessage onMessage(GateEditPreflightSnapshotPacket m,MessageContext c){if(m.isValid())Main.proxy.handleGateEditPreflightSnapshot(m);return null;}}
}
